[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["covid19_statistics_to_email"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/ManualTrigger","Category/Integration"]
  name = "covid19_statistics_to_email"
  org = "wso2cs"
  version = "3.1.1"

